name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}

    outputs:
      coveralls: ${{ steps.changes.outputs.src }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'package.json'
              - 'tsconfig.json'
            src:
              - 'src/**'
              - 'package.json'
            test:
              - 'test/**'
              - 'karma.conf.js'
              - 'package.json'
            types:
              - 'types/**'
              - 'package.json'
              - 'tsconfig.json'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        if: |
          steps.changes.outputs.src == 'true' ||
          steps.changes.outputs.test == 'true'
        run: |
          npm run build
          if [ "${{ runner.os }}" == "Windows" ]; then
            npm test
          elif [ "${{ runner.os }}" == "macOS" ]; then
            npm test --browsers chrome,safari
          else
            xvfb-run --auto-servernum npm test
          fi
        shell: bash
      - name: Lint
        run: npm run lint
      - name: Coveralls Parallel - Chrome
        if: steps.changes.outputs.src == 'true'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: './coverage/chrome/lcov.info'
          flag-name: ${{ matrix.os }}-chrome
          parallel: true
      - name: Coveralls Parallel - Firefox
        if: steps.changes.outputs.src == 'true'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: './coverage/firefox/lcov.info'
          flag-name: ${{ matrix.os }}-firefox
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        if: needs.build.outputs.coveralls == 'true'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
